Fix build error on iOS
aaassseee/screen_brightness pull request #4
Opened 2021-12-07 09:37 UTC by niku

I fixed a following error. It caused at building for iOS app using `flutter build ios --no-codesign` command.

```
screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift:89:78: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(Double(currentBrightness))
                                                                     ^
                                                                     CGFloat(                 )
```

<details>
<summary>Before fixed</summary>

```
~/src/screen_brightness/screen_brightness_ios/example develop
❯ git show && flutter clean && flutter doctor && flutter build ios --no-codesign
commit bf376f8b57e8113c582c20bd5082614b220d852a (HEAD -> develop)
Author: niku <10890+niku@users.noreply.github.com>
Date:   Tue Dec 7 17:46:15 2021 +0900

    Relax support version

diff --git a/screen_brightness_ios/example/pubspec.yaml b/screen_brightness_ios/example/pubspec.yaml
index b45ec6e..a71145f 100644
--- a/screen_brightness_ios/example/pubspec.yaml
+++ b/screen_brightness_ios/example/pubspec.yaml
@@ -6,7 +6,7 @@ description: Demonstrates how to use the screen_brightness_ios plugin.
 publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 environment:
-  sdk: ">=2.15.0-116.0.dev <3.0.0"
+  sdk: ">=2.12.0 <3.0.0"

 # Dependencies specify other packages that your package needs in order to work.
 # To automatically upgrade your package dependencies to the latest versions
Cleaning Xcode workspace...                                         3.4s
Deleting .dart_tool...                                               3ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!
Running "flutter pub get" in example...                            628ms
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.aaassseee.screenBrightnessIosExample for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...                                           1,534ms
Running Xcode build...
Xcode build done.                                            3.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/niku/src/screen_brightness/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift:89:78: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
            currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(Double(currentBrightness))
                                                                                 ^
                                                                                 CGFloat(                 )
    /Users/niku/src/screen_brightness/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift:89:78: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
            currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(Double(currentBrightness))
                                                                                 ^
                                                                                 CGFloat(                 )
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team.
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
```

</details>
<details>
<summary>After fixed</summary>

```
~/src/screen_brightness/screen_brightness_ios/example develop ⇡
❯ git show && flutter clean && flutter doctor && flutter build ios --no-codesign
commit bcf2ae46047165d625c7c30b2bb6263361ca0088 (HEAD -> develop, niku/develop)
Author: niku <10890+niku@users.noreply.github.com>
Date:   Tue Dec 7 17:52:01 2021 +0900

    Fix Xcode's build error

    screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift:89:78: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
    currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(Double(currentBrightness))
                                                                         ^
                                                                         CGFloat(                 )

diff --git a/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift b/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
index 841c923..96e2d5e 100644
--- a/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
+++ b/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
@@ -86,7 +86,7 @@ public class SwiftScreenBrightnessIosPlugin: NSObject, FlutterPlugin, FlutterApp
     }

     public func handleCurrentBrightnessChanged(_ currentBrightness: CGFloat) {
-        currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(Double(currentBrightness))
+        currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(CGFloat(currentBrightness))
     }

     @objc private func onSystemBrightnessChanged(notification: Notification) {
Cleaning Xcode workspace...                                         3.7s
Deleting build...                                                  140ms
Deleting .dart_tool...                                              28ms
Deleting .packages...                                                2ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            2ms
Deleting Flutter.podspec...                                          1ms
Deleting .flutter-plugins-dependencies...                            1ms
Deleting .flutter-plugins...                                         2ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on  [...]

2021-12-07 09:54 UTC, aaassseee commented
I am not facing the error that you got by calling flutter build ios --no-codesign. What is your environment?

2021-12-07 10:31 UTC, niku commented
I'm sorry my lack of explanation.
I guess it related on Xcode environment.

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    ja-JP)
    • Flutter version 2.5.3 at
      /Users/niku/.asdf/installs/flutter/2.5.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/niku/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/niku/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 96.0.4664.93

• No issues found!
```

2021-12-07 10:40 UTC, niku commented
I find my swift version is 5.4.2.

```
❯ swift --version
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: x86_64-apple-darwin20.6.0
```

It might have been fixed on 5.5 by following proposal.
https://github.com/apple/swift-evolution/blob/main/proposals/0307-allow-interchangeable-use-of-double-cgfloat-types.md
What is your swift version?

2021-12-07 11:21 UTC, aaassseee commented
I am currently out of office, so I didn't have any mac nearby. Maybe I can review and answer you tomorrow.

2021-12-08 01:18 UTC, aaassseee commented
My swift version is 
```
swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
Target: x86_64-apple-macosx11.0
```

2021-12-08 01:23 UTC, aaassseee requested changes
I found what I have done wrong
In https://github.com/aaassseee/screen_brightness/blob/236565cf85fbe6d10d89d6f42bac0b26f9301bf6/screen_brightness_ios/ios/Classes/StreamHandler/CurrentBrightnessChangeStreamHandler.swift#L13
is accepting CGFloat

May you please remove the object cast in https://github.com/aaassseee/screen_brightness/blob/bcf2ae46047165d625c7c30b2bb6263361ca0088/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift#L89
and test it again?

2021-12-08 05:42 UTC, niku commented
[After removing the object cast](https://github.com/aaassseee/screen_brightness/pull/4/commits/431bd2ae0390eea23fc78434d2c673662a2c807a), it looks work well 👏 

<details>

```
~/src/screen_brightness/screen_brightness_ios/example develop ⇡
❯ git show && flutter clean && flutter build ios --no-codesign
commit 431bd2ae0390eea23fc78434d2c673662a2c807a (HEAD -> develop, niku/develop)
Author: niku <10890+niku@users.noreply.github.com>
Date:   Wed Dec 8 14:35:45 2021 +0900

    Remove needless casting

diff --git a/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift b/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
index 96e2d5e..8a3f209 100644
--- a/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
+++ b/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift
@@ -86,7 +86,7 @@ public class SwiftScreenBrightnessIosPlugin: NSObject, FlutterPlugin, FlutterApp
     }

     public func handleCurrentBrightnessChanged(_ currentBrightness: CGFloat) {
-        currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(CGFloat(currentBrightness))
+        currentBrightnessChangeStreamHandler.addCurrentBrightnessToEventSink(currentBrightness)
     }

     @objc private func onSystemBrightnessChanged(notification: Notification) {
Cleaning Xcode workspace...                                         3.1s
Deleting build...                                                  160ms
Deleting .dart_tool...                                              22ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          1ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in example...                            604ms
Warning: Building for device with codesigning disabled. You will have to
manually codesign before deploying to device.
Building com.aaassseee.screenBrightnessIosExample for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file
version field before submitting to the App Store.
Running pod install...                                           1,443ms
Running Xcode build...
 └─Compiling, linking and signing...                         4.4s
Xcode build done.                                           34.8s
Built
/Users/niku/src/screen_brightness/screen_brightness_ios/example/build/ios/
iphoneos/Runner.app.
```

</details>

2021-12-08 06:06 UTC, aaassseee approved these changes
LGTM

2021-12-08 06:11 UTC, merged